### ISSUE TITLE
Notification.primary is not working

### ISSUE THREAD

**Issue by harryjoy** [alexcrack/angular-ui-notification#6]
Using the min.js file and calling simply ```Notification.primary('Primary notification');``` as shown in the example, but it gives following error.

```
 ReferenceError: args is not defined
    at Function.m.primary (http://localhost:9000/bower_components/angular-ui-notification/dist/angular-ui-notification.min.js:8:1568)
    at new <anonymous> (http://localhost:9000/app/home/home.controller.js:6:16)
    at invoke (http://localhost:9000/bower_components/angular/angular.js:4182:17)
    at Object.instantiate (http://localhost:9000/bower_components/angular/angular.js:4190:27)
    at http://localhost:9000/bower_components/angular/angular.js:8449:28
    at http://localhost:9000/bower_components/angular-ui-router/release/angular-ui-router.js:3897:28
    at invokeLinkFn (http://localhost:9000/bower_components/angular/angular.js:8213:9)
    at nodeLinkFn (http://localhost:9000/bower_components/angular/angular.js:7722:11)
    at compositeLinkFn (http://localhost:9000/bower_components/angular/angular.js:7075:13)
    at publicLinkFn (http://localhost:9000/bower_components/angular/angular.js:6954:30) 
```

All other functions works just well.
I installed it from bower. The version I got is v0.0.2.

Most probably the problem is missing args as argument in primary function. Here is the current definition:

```
notify.primary = function() {
   this(args, '');
};
```

It should have args as argument to the function. That might solve the problem. When I tried to do that it hanged my whole application saying "232VM1570:26054 WARNING: Tried to load angular more than once." and it goes infinitely loading process.

**Comment by alexcrack** [comment]
Thank you
